name: build

on:
  repository_dispatch:
    types: [build]
  push:
    branches:
      - master

jobs:
  build:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - run: echo "Update!"
